[package]
name = "_3-6-struct-as-files"
version = "0.1.0"
authors = ["ltbringer <amresh.venugopal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
